compatibility_date = "2022-02-15"
name = "g-assets"
type = "javascript"
account_id = "2db2112b269ed3616ed3a863a222f3e8"
workers_dev = true
zone_id = "7600c132f040aea60b0533ad801986d5"
routes = ["cdn.digitalclouds.dev/*"]
kv_namespaces = [
         { binding = "CDN", id = "b585bd3cfb294b5584434ac268734ac0" }
]