name = "digital-clouds-assets"
type = "webpack"
account_id = "2db2112b269ed3616ed3a863a222f3e8"

# workers_dev = true

route = "assets.digitalclouds.dev/*"
zone_id = "7600c132f040aea60b0533ad801986d5"
