name: Cloudlfare Workers

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cloudflare/wrangler-action@1.3.0
      with:        
        apiKey: ${{ secrets.CF_API_KEY }}
        email: ${{ secrets.CF_EMAIL }}
        publish: true
        preCommands: wrangler build
